export const events = [
    {
        title: "JS Conf 2026",
        image: "/images/event1.png",
        slug: "js-conf-2026",
        location: "Berlin, Germany",
        date: "2026-06-15",
        time: "09:00 AM",
    },
    {
        title: "Next.js Global Summit",
        image: "/images/event2.png",
        slug: "nextjs-global-summit",
        location: "San Francisco, USA",
        date: "2026-10-22",
        time: "10:00 AM",
    },
    {
        title: "React Day Berlin",
        image: "/images/event3.png",
        slug: "react-day-berlin",
        location: "Berlin, Germany",
        date: "2026-12-05",
        time: "08:30 AM",
    },
    {
        title: "Web Summit 2026",
        image: "/images/event4.png",
        slug: "web-summit-2026",
        location: "Lisbon, Portugal",
        date: "2026-11-01",
        time: "11:00 AM",
    },
    {
        title: "DevOps Days Austin",
        image: "/images/event5.png",
        slug: "devops-days-austin",
        location: "Austin, USA",
        date: "2026-05-12",
        time: "09:30 AM",
    },
    {
        title: "AI Hackathon",
        image: "/images/event6.png",
        slug: "ai-hackathon",
        location: "Online / Global",
        date: "2026-04-20",
        time: "12:00 PM",
    },
];
